language: node_js

node_js:
  - '20'
  - '18'
  - '16'
  - 'lts/*'

os:
  - linux
  - osx
  - windows

script:
  - npm run build
  - npm run lint
  - npm run format:check
  - npm test
# Coverage reporting removed - update to modern coverage tools if needed
