name: Build, Version Bump, and Publish to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run build process
      - name: Build project
        run: npm run build

      # 5. Run quality checks
      - name: Run linting
        run: npm run lint

      - name: Run format check
        run: npm run format:check

      # 6. Run tests
    #   - name: Run tests
    #     run: npm run jest:test

      # 7. Configure git user
      - name: Configure git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      # 8. Bump version
      - name: Bump version
        run: npm version patch

      # 9. Push changes
      - name: Push changes and tags
        run: |
          git push origin HEAD
          git push origin --tags

      # 10. Publish to npm
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
